---
title: "R Workshop : Marine Research"
output:
  html_document:
    css: "style.css"
    toc: false
---


This website accompanies the online workshop for *WUR Marine Research*, May/June 2021.

<br>



<div class = "training-card">

<div class = "training-label">
<span>Training 1</span>
</div>


## Programmer's skills

In this presentation, I illustrate a number of basic and must-know skills for the better R programmers.

[Slides on Programmer's skills](02_programming.html)

See also [Chapter 1 in A Learning Guide to R](https://remkoduursma.github.io/learningguidetor/intro.html) for some of the topics, and [Chapter 7](https://remkoduursma.github.io/learningguidetor/masteringpackages.html) for R package management.

## Version control with git

Use git version control to perfectly track the history of your code, and avoid problems.


[Slides on intro to git](03_versioncontrol.html)

See also [Chapter 5 : Version control with git](https://remkoduursma.github.io/learningguidetor/versioncontrol.html).

### Video

Edited recording of the first training (1h45m).

[Link to Youtube video](https://youtu.be/xcMrQQ6EDDg)

The video is unlisted (it will not appear in search results). Please do not share publicly.



</div>

<br>


<div class = "training-card">

<div class = "training-label">
<span>Training 2</span>
</div>





## Project management

In this presentation, I summarize and illustrate ten properties of "good" R projects.

[Slides on Project management](04_workflowtalk.html)

See also [Chapter 6 : Project management and workflow](https://remkoduursma.github.io/learningguidetor/projectman.html).

### Example Project

Take a look at an example project which demonstrates many of the concepts in the presentation on project management. 

[Example Project on Github](https://github.com/RemkoDuursma/almereparking)

Not included in the repository is a configuration file ([download it here](data/config.yml)), it needs to be placed in a subdirectory `conf/` in the project (the project runs without it though).

### Video

Edited recording of the second training (1h36m).

[Link to Youtube video](https://youtu.be/xcMrQQ6EDDg)

- Version control: collaborating, command line
- Project management: ten important ideas


</div>

<br>

<div class = "training-card">
<div class = "training-label">
<span>Training 3</span>
</div>

## Writing functions

In this training I will demonstrate writing functions, to improve organization, readability, reproducability, and reusability.

See also [Chapter 4 : Functions, lists and loops](https://remkoduursma.github.io/learningguidetor/programming.html).

### Video

Edited recording of the second training (1h36m).

[Link to Youtube video](https://www.youtube.com/watch?v=_RIrGbZgY1g)

- Demonstration of writing functions, working with lists.



</div>

<br>


<div class = "training-card">
## Reading

More background reading on project management, git version control, R package management, programming, and many other topics:

<span style="font-size: 1.4em">[A Learning Guide to R](https://remkoduursma.github.io/learningguidetor)</span>

by [Remko Duursma](https://www.remkoduursma.com)
</div>
